name: ServerMonitor
version: 1.0.0
main: io.papermc.sm.Main
description: Server performance monitoring
author: pairnon
website: https://github.com/pairnon/ServerMonitor
api-version: '1.20'
commands:
  toggleram:
    description: Toggle server memory usage bar
    usage: /toggleram
  toggletps:
    description: Toggle server tps bar
    usage: /toggletps